version: '3'
services:
  actix-diesel-rust:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ARGON_SALT: ${ARGON_SALT}
      SETTING_RUST_LOG: ${SETTING_RUST_LOG}
      SETTING_POOL_SIZE: ${SETTING_POOL_SIZE}
